/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectobanco.presentacion;

import com.mycompany.proyectobanco.entidades.Cuenta;
import com.mycompany.proyectobanco.negocio.ICuentasBO;
import com.mycompany.proyectobanco.negocio.IOperacionBO;
import com.mycompany.proyectobanco.negocio.ITransferenciaBO;
import com.mycompany.proyectobanco.negocio.NegocioException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class CambiarEstadoCuentaFORM extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CambiarEstadoCuentaFORM.class.getName());
    private final ICuentasBO cuentasBO;

    /**
     * Creates new form CambiarEstadoCuentaFORM
     */
    public CambiarEstadoCuentaFORM(ICuentasBO cuentasBO) {
        this.cuentasBO = cuentasBO;
        initComponents();
        this.llenarCuentasCliente();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        comboCuentasCliente = new javax.swing.JComboBox<>();
        lblCuentaCambiar = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnCambiarEstado = new javax.swing.JButton();
        lblEstadoActual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        comboCuentasCliente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        comboCuentasCliente.setForeground(new java.awt.Color(0, 0, 0));
        comboCuentasCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        comboCuentasCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboCuentasCliente.addItemListener(this::comboCuentasClienteItemStateChanged);
        comboCuentasCliente.addActionListener(this::comboCuentasClienteActionPerformed);

        lblCuentaCambiar.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblCuentaCambiar.setForeground(new java.awt.Color(0, 0, 0));
        lblCuentaCambiar.setText("Seleccione la cuenta: ");

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Cambiar Estado de Cuenta");

        btnCambiarEstado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCambiarEstado.setForeground(new java.awt.Color(0, 0, 0));
        btnCambiarEstado.setText("Cambiar estado");
        btnCambiarEstado.addActionListener(this::btnCambiarEstadoActionPerformed);

        lblEstadoActual.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEstadoActual.setForeground(new java.awt.Color(0, 0, 0));
        lblEstadoActual.setText("Estado Actual de la Cuenta:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblEstadoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitulo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCuentaCambiar)
                                .addGap(23, 23, 23)))
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(comboCuentasCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCambiarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCuentaCambiar)
                .addGap(18, 18, 18)
                .addComponent(comboCuentasCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161)
                .addComponent(lblEstadoActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCambiarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboCuentasClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCuentasClienteItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            Cuenta cuenta = (Cuenta) comboCuentasCliente.getSelectedItem();
            if (cuenta != null) {
                lblEstadoActual.setText("estado actual de la cuenta: " + cuenta.getEstado());
            }
        }
    }//GEN-LAST:event_comboCuentasClienteItemStateChanged

    private void llenarCuentasCliente() {
        try {
            List<Cuenta> cuentasClientes = cuentasBO.consultarCuentasCliente(1l); //Aqui se cambiara a que sea el id del usuario que inicio sesion,
            // esta para poder probar el CU transferencia
            comboCuentasCliente.removeAllItems();

            for (Cuenta cuenta : cuentasClientes) {
                comboCuentasCliente.addItem(cuenta);
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al consultar cuentas del cliente: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    private void comboCuentasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCuentasClienteActionPerformed

    }//GEN-LAST:event_comboCuentasClienteActionPerformed

    private void btnCambiarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarEstadoActionPerformed
        this.cambiarEstado();
    }//GEN-LAST:event_btnCambiarEstadoActionPerformed

    private void cambiarEstado() {
        Cuenta cuentaCliente = (Cuenta) comboCuentasCliente.getSelectedItem();
        String numeroCuenta = cuentaCliente.getNumeroCuenta();
        try {
            this.cuentasBO.cambiarEstadoCuenta(numeroCuenta);
            JOptionPane.showMessageDialog(
                    this,
                    "Se ha cambiado el estado de cuenta correctamente",
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE
            );
            llenarCuentasCliente();
            comboCuentasCliente.setSelectedIndex(0);
           
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al cambiar el estado de cuenta: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarEstado;
    private javax.swing.JComboBox<Cuenta> comboCuentasCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCuentaCambiar;
    private javax.swing.JLabel lblEstadoActual;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
