
package com.mycompany.proyectobanco.presentacion;

import com.mycompany.proyectobanco.dtos.CobrarRetiroDTO;
import com.mycompany.proyectobanco.dtos.ObjetosBoDTO;
import com.mycompany.proyectobanco.entidades.Retiro.Estado;
import com.mycompany.proyectobanco.negocio.NegocioException;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Julian
 */
public class CobrarRetiroSinCuentaFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CobrarRetiroSinCuentaFORM.class.getName());
    private Timer timer;
    private final int TIEMPO_LIMITE = 10 * 60; 
    private int segundosRestantes = TIEMPO_LIMITE;
    private Estado estado;
    private final ObjetosBoDTO objetosBO;

    /**
     * Creates new form CobrarRetiroSinCuentaFORM
     * @param objetosBO
     */
    public CobrarRetiroSinCuentaFORM(ObjetosBoDTO objetosBO) {
        this.objetosBO = objetosBO;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtFolioOperacion = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JTextField();
        lblFolioOperacion = new javax.swing.JLabel();
        lblContrasenia = new javax.swing.JLabel();
        btnRetirar = new javax.swing.JButton();
        btnVolverAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Cobrar Retiro Sin Cuenta");

        txtFolioOperacion.setBackground(new java.awt.Color(255, 255, 255));
        txtFolioOperacion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtFolioOperacion.setForeground(new java.awt.Color(0, 0, 0));
        txtFolioOperacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtContrasenia.setBackground(new java.awt.Color(255, 255, 255));
        txtContrasenia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtContrasenia.setForeground(new java.awt.Color(0, 0, 0));
        txtContrasenia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblFolioOperacion.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblFolioOperacion.setForeground(new java.awt.Color(0, 0, 0));
        lblFolioOperacion.setText("Ingrese el folio de operacion: ");

        lblContrasenia.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblContrasenia.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasenia.setText("Ingrese la contraseña:");

        btnRetirar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRetirar.setForeground(new java.awt.Color(0, 0, 0));
        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(this::btnRetirarActionPerformed);

        btnVolverAtras.setBackground(new java.awt.Color(153, 153, 153));
        btnVolverAtras.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnVolverAtras.setForeground(new java.awt.Color(0, 0, 0));
        btnVolverAtras.setText(">");
        btnVolverAtras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVolverAtras.addActionListener(this::btnVolverAtrasActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblContrasenia)
                        .addGap(283, 283, 283))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFolioOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFolioOperacion)
                            .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(251, 251, 251))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnVolverAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(269, 269, 269))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo))
                    .addComponent(btnVolverAtras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(lblFolioOperacion)
                .addGap(18, 18, 18)
                .addComponent(txtFolioOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(lblContrasenia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        this.cobrarRetiro();
        vaciarForm();
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAtrasActionPerformed
        volverAtras();
    }//GEN-LAST:event_btnVolverAtrasActionPerformed

    private void cobrarRetiro(){
        try {
            String folioOperacion = txtFolioOperacion.getText();
            String contrasenia = txtContrasenia.getText();
            
            
            CobrarRetiroDTO retiroDTO = new CobrarRetiroDTO(folioOperacion,contrasenia,estado);
            objetosBO.getRetiroBO().cobrarRetiroSinCuenta(retiroDTO);
            
            JOptionPane.showMessageDialog(this, "Retiro cobrado exitosamente.", 
                "Cobro realizado correctamente.", 
                JOptionPane.INFORMATION_MESSAGE);
            
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al cobrar el retiro: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void vaciarForm(){
        txtFolioOperacion.setText("");
        txtContrasenia.setText("");
    }
    
    private void volverAtras(){
        vaciarForm();
        this.dispose();
        new InicioSesionFORM(objetosBO).setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnVolverAtras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblFolioOperacion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtFolioOperacion;
    // End of variables declaration//GEN-END:variables
}
