/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectobanco.presentacion;

import com.mycompany.proyectobanco.dtos.ObjetosBoDTO;
import com.mycompany.proyectobanco.entidades.Cliente;
import com.mycompany.proyectobanco.entidades.Cuenta;
import com.mycompany.proyectobanco.entidades.Operacion;
import com.mycompany.proyectobanco.negocio.ICuentasBO;
import com.mycompany.proyectobanco.negocio.IHistorialOperacionesBO;
import com.mycompany.proyectobanco.negocio.NegocioException;
import com.mycompany.proyectobanco.persistencia.PersistenciaException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BALAMRUSH
 */
public class ConsultarHIstorialOPeracionFORM extends javax.swing.JFrame {
    
    private ObjetosBoDTO objetosBO;
    private Cliente cliente;
    

    /**
     * Creates new form ConsultarHIstorialOPeracionFORM
     */
    public ConsultarHIstorialOPeracionFORM(ObjetosBoDTO objetosBO, Cliente cliente) {
        this.objetosBO = objetosBO;
        this.cliente = cliente;
        initComponents();
        cargarCuentas();
        cargarTipoOperacion();
    }
    
    private void cargarCuentas(){
        try{
            List<Cuenta> cuentas = objetosBO.getCuentasBO().consultarCuentasCliente(Long.valueOf(cliente.getIdCliente()));
            comboCuentas.removeAllItems();
            for(Cuenta cuenta: cuentas){
                comboCuentas.addItem(cuenta.getNumeroCuenta());
            }
        }catch(NegocioException ex){
            JOptionPane.showMessageDialog(this,"Error al cargar las cuentas: " + ex.getMessage(),"Error", JOptionPane.ERROR_MESSAGE);;
        }
    }
    
    private void cargarTipoOperacion(){
        comboTipoOperacion.removeAllItems();
        comboTipoOperacion.addItem("Todas");
        comboTipoOperacion.addItem("Transferencia");
        comboTipoOperacion.addItem("Retiro sin cuenta");
    }
    
    private void actualizarTabla() throws NegocioException{
        String numeroCuenta = (String) comboCuentas.getSelectedItem();
        String tipoSeleccionado = (String) comboTipoOperacion.getSelectedItem();
        if(numeroCuenta == null || tipoSeleccionado == null){
            return;
        }
        
        try{
            List<Operacion> operaciones;
            
            switch(tipoSeleccionado){
                case "Transferencia"  -> operaciones = objetosBO.getHistorialBO().consultarTransferenciaCuenta(numeroCuenta);
                case "Retiro sin cuenta" -> operaciones = objetosBO.getHistorialBO().consultarRetirosPorCuenta(numeroCuenta);
                default -> operaciones = objetosBO.getHistorialBO().consultarOperacionesCuenta(numeroCuenta);
            }
            
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0);
            
            for(Operacion op: operaciones){
                modelo.addRow(new Object[]{
                    op.getIdOperacion(),
                    op.getMonto(),
                    op.getFechaHora(),
                    op.getNumeroCuenta()
                });
            }
            
            if(operaciones.isEmpty()){
                JOptionPane.showMessageDialog(this,"No existen operaciones para los filtros seleccionados.","Sin resultados", JOptionPane.INFORMATION_MESSAGE);
            }
            }catch(NegocioException ex){
                JOptionPane.showMessageDialog(this,"Error al consultar el historial: " + ex.getMessage(),"Error", JOptionPane.ERROR_MESSAGE);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        comboCuentas = new javax.swing.JComboBox<>();
        comboTipoOperacion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Monto", "FechaHora", "Num. Cuenta"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        comboCuentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboTipoOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboTipoOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoOperacionActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero Cuenta");

        jLabel2.setText("Tipo Operacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboCuentas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(comboTipoOperacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboTipoOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTipoOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoOperacionActionPerformed
//        actualizarTabla();
    }//GEN-LAST:event_comboTipoOperacionActionPerformed
    private void comboCuentaActioPerormed(java.awt.event.ActionEvent evt) {                                                   
//        actualizarTabla();
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboCuentas;
    private javax.swing.JComboBox<String> comboTipoOperacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
