/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectobanco.presentacion;

import com.mycompany.proyectobanco.dtos.HistorialOperacionesDTO;
import com.mycompany.proyectobanco.negocio.CuentasBO;
import com.mycompany.proyectobanco.negocio.HistorialOperacionesBO;
import com.mycompany.proyectobanco.negocio.NegocioException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BALAMRUSH
 */
public class ConsultarHistorialOperacionesFORM extends javax.swing.JFrame {
    private HistorialOperacionesBO historialOperacionesBO;

    /**
     * Creates new form ConsultarHistorialOperacionesFORM
     */
    public ConsultarHistorialOperacionesFORM() throws NegocioException {
        historialOperacionesBO = new HistorialOperacionesBO();
        initComponents();
        cargarDatosCuentas();
        cargarDatosTiposOperaciones();
    }
    
    private void cargarDatosCuentas(){
        try{
            cuentaCombo.removeAllItems();
            cuentaCombo.addItem("TODAS");
            for(String cuenta: historialOperacionesBO.obtenerNumerosCuenta()){
                cuentaCombo.addItem(cuenta);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Hubo un error al cargar las cuentas");
        }
    }
    
    private void cargarDatosTiposOperaciones(){
        tipoOperacionCombo.removeAllItems();
        tipoOperacionCombo.addItem("TODOS");
        tipoOperacionCombo.addItem("RETIRO");
        tipoOperacionCombo.addItem("TRANSFERENCIA");
    }
    
    private void actualizarTabla(){
        if(cuentaCombo.getSelectedItem()== null || tipoOperacionCombo.getSelectedItem()== null){
            return;
        }
        try{
            String cuenta = cuentaCombo.getSelectedItem().toString();
            String tipo = tipoOperacionCombo.getSelectedItem().toString();
            
            if(cuenta.equals("TODAS")){
                cuenta = null;
            }
            
            if(cuenta.equals("TODOS")){
                tipo = null;
            }
            var lista = historialOperacionesBO.consultarHistorialOperaciones(cuenta, tipo);
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0);
            for(HistorialOperacionesDTO historialDTO: lista){
                modelo.addRow(new Object[]{
                    historialDTO.getIdOperacion(),
                    historialDTO.getMonto(),
                    historialDTO.getFechaHora(),
                    historialDTO.getTipo()
                });
            }

        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Hubo un error"+ex.getMessage());
        }
 
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cuentaCombo = new javax.swing.JComboBox<>();
        tipoOperacionCombo = new javax.swing.JComboBox<>();
        cuentaLabel = new javax.swing.JLabel();
        tipoOperacionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        cuentaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cuentaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaComboActionPerformed(evt);
            }
        });

        tipoOperacionCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tipoOperacionCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoOperacionComboActionPerformed(evt);
            }
        });

        cuentaLabel.setText("Cuenta");

        tipoOperacionLabel.setText("Tipo de Operación");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Monto", "Fecha", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cuentaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipoOperacionCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cuentaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipoOperacionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(cuentaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cuentaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(tipoOperacionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tipoOperacionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cuentaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaComboActionPerformed
       actualizarTabla();
    }//GEN-LAST:event_cuentaComboActionPerformed

    private void tipoOperacionComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoOperacionComboActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_tipoOperacionComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cuentaCombo;
    private javax.swing.JLabel cuentaLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> tipoOperacionCombo;
    private javax.swing.JLabel tipoOperacionLabel;
    // End of variables declaration//GEN-END:variables
}
