/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectobanco.presentacion;

import com.mycompany.proyectobanco.dtos.ObjetosBoDTO;
import com.mycompany.proyectobanco.entidades.Cliente;
import com.mycompany.proyectobanco.entidades.Cuenta;
import com.mycompany.proyectobanco.entidades.Operacion;
import com.mycompany.proyectobanco.negocio.ICuentasBO;
import com.mycompany.proyectobanco.negocio.IHistorialOperacionesBO;
import com.mycompany.proyectobanco.negocio.NegocioException;
import com.mycompany.proyectobanco.persistencia.HistorialOperacioneDAO;
import com.mycompany.proyectobanco.persistencia.IHistorialOperacionesDAO;
import com.mycompany.proyectobanco.persistencia.IOperacionDAO;
import com.mycompany.proyectobanco.persistencia.OperacionDAO;
import com.mycompany.proyectobanco.persistencia.PersistenciaException;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.print.attribute.standard.DateTimeAtCompleted;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BALAMRUSH
 */
public class ConsultarHIstorialOPeracionFORM extends javax.swing.JFrame {
    
    private ObjetosBoDTO objetosBO;
    private Cliente cliente;
    

    /**
     * Creates new form ConsultarHIstorialOPeracionFORM
     */
    public ConsultarHIstorialOPeracionFORM(ObjetosBoDTO objetosBO, Cliente cliente) {
        this.objetosBO = objetosBO;
        this.cliente = cliente;
        initComponents();
        cargarCuentas();
        cargarTipoOperacion();
    }
    
    private void cargarCuentas(){
        try{
            List<Cuenta> cuentas = objetosBO.getCuentasBO().consultarCuentasCliente(Long.valueOf(cliente.getIdCliente()));
            comboCuentas.removeAllItems();
            for(Cuenta cuenta: cuentas){
                comboCuentas.addItem(cuenta.getNumeroCuenta());
            }
        }catch(NegocioException ex){
            JOptionPane.showMessageDialog(this,"Error al cargar las cuentas: " + ex.getMessage(),"Error", JOptionPane.ERROR_MESSAGE);;
        }
    }
    
    private void cargarTipoOperacion(){
        comboTipoOperacion.removeAllItems();
        comboTipoOperacion.addItem("Transferencia");
        comboTipoOperacion.addItem("Retiro sin cuenta");
    }
    
    private void actualizarTabla(List<Operacion> operacion) {
        String[] columnas = {"ID Operacion", "Numero de Cuentas", "Monto", "Fecha Hora"
            
        };
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        DateTimeFormatter formatoFechaHora = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        
        for(Operacion op: operacion){
            modelo.addRow(new Object[]{
                op.getIdOperacion(),
                op.getNumeroCuenta(),
                op.getMonto(),
                op.getFechaHora().format(formatoFechaHora)
            });
        }
        jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        comboCuentas = new javax.swing.JComboBox<>();
        comboTipoOperacion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mostrarDatosButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Operacion", "Numero de Cuenta", "Monto", "Fecha Hora"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        comboCuentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboTipoOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboTipoOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoOperacionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Numero Cuenta");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tipo Operacion");

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText(">");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mostrarDatosButton.setText("Mostrar");
        mostrarDatosButton.setAutoscrolls(true);
        mostrarDatosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarDatosButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Historial Operaciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboCuentas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboTipoOperacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(mostrarDatosButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)))
                .addGap(64, 64, 64)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboTipoOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(mostrarDatosButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTipoOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoOperacionActionPerformed

    }//GEN-LAST:event_comboTipoOperacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MenuPrincipalFORM(objetosBO, cliente).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mostrarDatosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarDatosButtonActionPerformed
        try{
            String cuentaSeleccionada = (String) comboCuentas.getSelectedItem();
            String tipoSeleccionado = (String) comboTipoOperacion.getSelectedItem();
            
            IHistorialOperacionesDAO historialDAO = new HistorialOperacioneDAO();
            List<Operacion> lista;
            
            if(tipoSeleccionado.equalsIgnoreCase("Transferencia")){
                lista = historialDAO.consultarTrasnferenciaCuenta(cuentaSeleccionada);
            }else if(tipoSeleccionado.equalsIgnoreCase("Retiro sin cuenta")){
                lista = historialDAO.consultarRetirosCuenta(cuentaSeleccionada);
            }else{
                lista = historialDAO.consultarOperacionesCuenta(cuentaSeleccionada);
            }

            actualizarTabla(lista);
        }catch(PersistenciaException ex){
            JOptionPane.showMessageDialog(this, "Existe un error al querer consultar"+ex.getMessage());
        }        
        
        
    }//GEN-LAST:event_mostrarDatosButtonActionPerformed
    private void comboCuentaActioPerormed(java.awt.event.ActionEvent evt) {                                                   
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboCuentas;
    private javax.swing.JComboBox<String> comboTipoOperacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton mostrarDatosButton;
    // End of variables declaration//GEN-END:variables
}
