/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectobanco.presentacion;

import com.mycompany.proyectobanco.dtos.NuevoRetiroFormDTO;
import com.mycompany.proyectobanco.entidades.Cuenta;
import com.mycompany.proyectobanco.entidades.Retiro;
import com.mycompany.proyectobanco.entidades.Retiro.Estado;
import com.mycompany.proyectobanco.negocio.ICuentasBO;
import com.mycompany.proyectobanco.negocio.IRetiroBO;
import com.mycompany.proyectobanco.negocio.NegocioException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Julian
 */
public class GenerarRetiroSinCuentaFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GenerarRetiroSinCuentaFORM.class.getName());
    private final ICuentasBO cuentasBO;
    private final IRetiroBO retiroBO;

    /**
     * Creates new form GenerarRetiroSinCuentaFORM
     */
    public GenerarRetiroSinCuentaFORM(ICuentasBO cuentasBO, IRetiroBO retiroBO) {
        this.retiroBO = retiroBO;
        this.cuentasBO = cuentasBO;
        initComponents();
        this.llenarCuentasCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGenerarRetiroSinCuenta = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        comboCuentasCliente = new javax.swing.JComboBox<>();
        lblSeleccionCuentaOrigen = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        lblMonto = new javax.swing.JLabel();
        lblSaldoDisponible = new javax.swing.JLabel();
        btnGenerarRetiro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        pnlGenerarRetiroSinCuenta.setBackground(new java.awt.Color(153, 153, 153));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Generar Retiro Sin Cuenta");

        comboCuentasCliente.setBackground(new java.awt.Color(255, 255, 255));
        comboCuentasCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        comboCuentasCliente.addItemListener(this::cambioSaldoDisponibleCuenta);

        lblSeleccionCuentaOrigen.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblSeleccionCuentaOrigen.setForeground(new java.awt.Color(0, 0, 0));
        lblSeleccionCuentaOrigen.setText("Seleccione la cuenta origen: ");

        txtMonto.setBackground(new java.awt.Color(255, 255, 255));
        txtMonto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtMonto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMonto.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(0, 0, 0));
        lblMonto.setText("Ingrese el monto:");

        lblSaldoDisponible.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSaldoDisponible.setForeground(new java.awt.Color(0, 0, 0));
        lblSaldoDisponible.setText("Saldo Disponible: $");

        btnGenerarRetiro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGenerarRetiro.setForeground(new java.awt.Color(0, 0, 0));
        btnGenerarRetiro.setText("Generar Retiro");
        btnGenerarRetiro.addActionListener(this::btnGenerarRetiroActionPerformed);

        javax.swing.GroupLayout pnlGenerarRetiroSinCuentaLayout = new javax.swing.GroupLayout(pnlGenerarRetiroSinCuenta);
        pnlGenerarRetiroSinCuenta.setLayout(pnlGenerarRetiroSinCuentaLayout);
        pnlGenerarRetiroSinCuentaLayout.setHorizontalGroup(
            pnlGenerarRetiroSinCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGenerarRetiroSinCuentaLayout.createSequentialGroup()
                .addGroup(pnlGenerarRetiroSinCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGenerarRetiroSinCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlGenerarRetiroSinCuentaLayout.createSequentialGroup()
                            .addGap(252, 252, 252)
                            .addGroup(pnlGenerarRetiroSinCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblSeleccionCuentaOrigen)
                                .addGroup(pnlGenerarRetiroSinCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboCuentasCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlGenerarRetiroSinCuentaLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblTitulo)))))
                        .addGroup(pnlGenerarRetiroSinCuentaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(pnlGenerarRetiroSinCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSaldoDisponible)
                                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlGenerarRetiroSinCuentaLayout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(lblMonto))
                    .addGroup(pnlGenerarRetiroSinCuentaLayout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(btnGenerarRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        pnlGenerarRetiroSinCuentaLayout.setVerticalGroup(
            pnlGenerarRetiroSinCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGenerarRetiroSinCuentaLayout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addGap(90, 90, 90)
                .addComponent(lblSeleccionCuentaOrigen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboCuentasCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(lblMonto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSaldoDisponible)
                .addGap(38, 38, 38)
                .addComponent(btnGenerarRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGenerarRetiroSinCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGenerarRetiroSinCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void generarRetiroSinCuenta(){
        try {
            Cuenta cuentaOrigen = (Cuenta) comboCuentasCliente.getSelectedItem();
            Long montoRetiro = Long.valueOf(txtMonto.getText());
            LocalDateTime fechaHora = LocalDateTime.now();
            Estado estado = Estado.ACTIVO; 
            
            NuevoRetiroFormDTO retiroDTO = new NuevoRetiroFormDTO(montoRetiro,fechaHora,cuentaOrigen,estado);
            Retiro retiro = retiroBO.generarRetiroSinCuenta(retiroDTO);
            
            DateTimeFormatter formatterFechaHora = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
            String formatoFechaHora = fechaHora.format(formatterFechaHora);
            
            String mensaje = "Cuenta origen: "+cuentaOrigen.getNumeroCuenta()+"\n"
                    +"Monto: $"+montoRetiro+"\n"
                    +"Fecha: "+formatoFechaHora+"\n"
                    +"Folio Operacion: "+retiro.getFolioRetiro()+"\n"
                    +"Contrasenia: "+retiro.getContrasenia();
            
            JOptionPane.showMessageDialog(this, mensaje, 
            "Comprobante de Retiro Sin Cuenta", 
            JOptionPane.INFORMATION_MESSAGE);
            
            llenarCuentasCliente();
            vaciarForm();
            comboCuentasCliente.setSelectedIndex(0);
            
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al generar el retiro: " + ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void vaciarForm(){
        txtMonto.setText("");
    }
    
    private void cambioSaldoDisponibleCuenta(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cambioSaldoDisponibleCuenta
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            Cuenta cuenta = (Cuenta) comboCuentasCliente.getSelectedItem();
            if (cuenta != null) {
                lblSaldoDisponible.setText("Saldo Disponible: $" + cuenta.getSaldo());
            }
        }
    }//GEN-LAST:event_cambioSaldoDisponibleCuenta

    private void btnGenerarRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarRetiroActionPerformed
        this.generarRetiroSinCuenta();
    }//GEN-LAST:event_btnGenerarRetiroActionPerformed

    private void llenarCuentasCliente() {
        try {
            List<Cuenta> cuentasClientes = cuentasBO.consultarCuentasCliente(1); //Aqui se cambiara a que sea el id del usuario que inicio sesion,
            // esta para poder probar el CU transferencia
            comboCuentasCliente.removeAllItems();

            for (Cuenta cuenta : cuentasClientes) {
                comboCuentasCliente.addItem(cuenta);
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al consultar cuentas del cliente: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarRetiro;
    private javax.swing.JComboBox<Cuenta> comboCuentasCliente;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblSaldoDisponible;
    private javax.swing.JLabel lblSeleccionCuentaOrigen;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlGenerarRetiroSinCuenta;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
