/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectobanco.presentacion;

import com.mycompany.proyectobanco.dtos.NuevaTransferenciaFormDTO;
import com.mycompany.proyectobanco.dtos.ObjetosBoDTO;
import com.mycompany.proyectobanco.entidades.Cliente;
import com.mycompany.proyectobanco.entidades.Cuenta;
import com.mycompany.proyectobanco.negocio.NegocioException;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Julian
 */
public class SeleccionarCuentaOrigenTransferenciaFORM extends javax.swing.JFrame {

    private static final java.util.logging.Logger LOGGER = java.util.logging.Logger.getLogger(SeleccionarCuentaOrigenTransferenciaFORM.class.getName());
    
    private final ObjetosBoDTO objetosBO ;
    private Cliente clienteLogeado;
    
    /**
     * Creates new form SeleccionarCuentaOrigenTransferenciaFORM
     *
     * @param objetosBO
     */
    public SeleccionarCuentaOrigenTransferenciaFORM(ObjetosBoDTO objetosBO,Cliente clienteLogeado) {
        this.objetosBO = objetosBO;
        this.clienteLogeado = clienteLogeado;
        initComponents();
        this.llenarCuentasCliente();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboCuentasCliente = new javax.swing.JComboBox<>();
        lblCuentaOrigen = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblCuentaDestino = new javax.swing.JLabel();
        txtCuentaDestino = new javax.swing.JTextField();
        btnTransferir = new javax.swing.JButton();
        txtMontoATransferir = new javax.swing.JTextField();
        lblMontoATransferir = new javax.swing.JLabel();
        lblMostrarSaldoDisponible = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SeleccionarCuentaOrigen");
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        comboCuentasCliente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        comboCuentasCliente.setForeground(new java.awt.Color(0, 0, 0));
        comboCuentasCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        comboCuentasCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboCuentasCliente.addItemListener(this::comboCuentasClienteItemStateChanged);
        comboCuentasCliente.addActionListener(this::comboCuentasClienteActionPerformed);

        lblCuentaOrigen.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblCuentaOrigen.setForeground(new java.awt.Color(0, 0, 0));
        lblCuentaOrigen.setText("Seleccione la cuenta origen: ");

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Realizar Transferencia");

        lblCuentaDestino.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblCuentaDestino.setForeground(new java.awt.Color(0, 0, 0));
        lblCuentaDestino.setText("Ingrese la cuenta destino:");

        txtCuentaDestino.setBackground(new java.awt.Color(86, 86, 86));
        txtCuentaDestino.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtCuentaDestino.setForeground(new java.awt.Color(0, 0, 0));
        txtCuentaDestino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnTransferir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnTransferir.setForeground(new java.awt.Color(0, 0, 0));
        btnTransferir.setText("Transferir");
        btnTransferir.addActionListener(this::btnTransferirActionPerformed);

        txtMontoATransferir.setBackground(new java.awt.Color(86, 86, 86));
        txtMontoATransferir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtMontoATransferir.setForeground(new java.awt.Color(0, 0, 0));
        txtMontoATransferir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMontoATransferir.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblMontoATransferir.setForeground(new java.awt.Color(0, 0, 0));
        lblMontoATransferir.setText("Monto:");

        lblMostrarSaldoDisponible.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMostrarSaldoDisponible.setForeground(new java.awt.Color(0, 0, 0));
        lblMostrarSaldoDisponible.setText("Saldo Disponible: $");

        btnVolver.setBackground(new java.awt.Color(153, 153, 153));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver.setText(">");
        btnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(303, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCuentaDestino)
                        .addGap(270, 270, 270))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMontoATransferir, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(348, 348, 348))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMostrarSaldoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMontoATransferir, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCuentaOrigen)
                                    .addComponent(comboCuentasCliente, 0, 280, Short.MAX_VALUE)
                                    .addComponent(txtCuentaDestino))))
                        .addGap(251, 251, 251))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(276, 276, 276))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo))
                    .addComponent(btnVolver))
                .addGap(66, 66, 66)
                .addComponent(lblCuentaOrigen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboCuentasCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblCuentaDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMontoATransferir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMontoATransferir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMostrarSaldoDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vaciarFORM() {
        txtCuentaDestino.setText("");
        txtMontoATransferir.setText("");
    }
    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        this.realizarTransferencia();

    }//GEN-LAST:event_btnTransferirActionPerformed

    private void comboCuentasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCuentasClienteActionPerformed

    }//GEN-LAST:event_comboCuentasClienteActionPerformed

    private void comboCuentasClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCuentasClienteItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            Cuenta cuenta = (Cuenta) comboCuentasCliente.getSelectedItem();
            if (cuenta != null) {
                lblMostrarSaldoDisponible.setText("Saldo Disponible: $" + cuenta.getSaldo());
            }
        }
    }//GEN-LAST:event_comboCuentasClienteItemStateChanged

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        volverAtras();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void realizarTransferencia() {
        try {
            Cuenta cuentaOrigen = (Cuenta) comboCuentasCliente.getSelectedItem();
            String cuentaDestino = txtCuentaDestino.getText();
            Integer montoTransferencia = Integer.valueOf(txtMontoATransferir.getText());
            LocalDateTime fechaHora = LocalDateTime.now();

            NuevaTransferenciaFormDTO transferenciaFormDTO = new NuevaTransferenciaFormDTO(cuentaDestino,cuentaOrigen,montoTransferencia,fechaHora);
            this.objetosBO.getTransferenciaBO().crearTransferencia(transferenciaFormDTO);

            JOptionPane.showMessageDialog(
                    this,
                    "Transferencia realizada correctamente.",
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE
            );

            llenarCuentasCliente();
            vaciarFORM();
            comboCuentasCliente.setSelectedIndex(0);

        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error en transferencia: " + ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }

    }

    private void llenarCuentasCliente() {
        try {
            List<Cuenta> cuentasClientes = objetosBO.getCuentasBO().consultarCuentasCliente(Long.parseLong(clienteLogeado.getIdCliente()));
            comboCuentasCliente.removeAllItems();

            for (Cuenta cuenta : cuentasClientes) {
                comboCuentasCliente.addItem(cuenta);
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al consultar cuentas del cliente: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void volverAtras(){
        vaciarFORM();
        this.dispose();
        new MenuPrincipalFORM(objetosBO,clienteLogeado).setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransferir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<Cuenta> comboCuentasCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCuentaDestino;
    private javax.swing.JLabel lblCuentaOrigen;
    private javax.swing.JLabel lblMontoATransferir;
    private javax.swing.JLabel lblMostrarSaldoDisponible;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCuentaDestino;
    private javax.swing.JTextField txtMontoATransferir;
    // End of variables declaration//GEN-END:variables
}
